services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    ports:
      - "3000:1883" #puerto MQTT est√°ndar
    volumes:
      - ./mqtt/config/:/mosquitto/config
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
    restart: unless-stopped
  base_datos:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "3001:5432" # Puerto PostgreSQL
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ubicua
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init_scripts:/docker-entrypoint-initdb.d

volumes:
  postgres_data: